spring:
  application:
    name: backend-service

// cicd테스트 진행
  config:
    import: optional:configserver:http://43.203.226.189:8888/

logging:
  level:
    org.springframework.cloud.config.client: DEBUG
